version: "3"

services:

  avd:
    build: "./avd/"
    image: "exploit-android/avd"
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
      - DISPLAY=$DISPLAY
    network_mode: "host" 
    devices:
      - "/dev/kvm:/dev/kvm"

  rms:
    build: "./rms/"
    image: "exploit-android/rms"
    network_mode: "host" 
    depends_on:
      - avd
    ports:
      - "5000:5000"
